import { db, PRODUCTS_COLLECTION } from './firebase';
import { doc, setDoc, serverTimestamp } from 'firebase/firestore';

export const REAL_PRODUCTS = [
  {
    id: 'livotec-open-7-stage',
    name: 'Livotec Open (7 Stage RO)',
    model: 'AP-LIV-OPEN7',
    category: 'RO Purifiers',
    price: 16200,
    originalPrice: 19500,
    warranty: '1 Year Electrical',
    application: 'Household',
    stockStatus: 'In Stock' as const,
    featured: true,
    filterHealth: 100,
    imageUrl: 'https://res.cloudinary.com/rvoym2gw/image/upload/v1786130065/products/livotec_open.webp',
    description: '7-stage Reverse Osmosis drinking water purification system featuring an open frame structure for effortless maintenance and high-output mineral purification.'
  },
  {
    id: 'livotec-stand-7-stage',
    name: 'Livotec Stand (7 Stage RO)',
    model: 'AP-LIV-STD7',
    category: 'RO Purifiers',
    price: 17500,
    originalPrice: 20000,
    warranty: '1 Year Electrical',
    application: 'Household',
    stockStatus: 'In Stock' as const,
    featured: true,
    filterHealth: 100,
    imageUrl: 'https://res.cloudinary.com/rvoym2gw/image/upload/v1786130066/products/livotec_stand.webp',
    description: 'Sturdy standing frame 7-stage RO water purifier with integrated pressure gauge, mineral infusion, and high-efficiency membrane.'
  },
  {
    id: 'eureka-classic-7-stage',
    name: 'Eureka Classic (7 Stage RO)',
    model: 'AP-EUR-CLS7',
    category: 'RO Purifiers',
    price: 14500,
    originalPrice: 17000,
    warranty: '1 Year Electrical',
    application: 'Household',
    stockStatus: 'In Stock' as const,
    featured: true,
    filterHealth: 100,
    imageUrl: 'https://res.cloudinary.com/rvoym2gw/image/upload/v1786130067/products/eureka_classic.webp',
    description: 'Reliable household 7-stage RO purifier engineered for maximum TDS reduction and crisp drinking water.'
  },
  {
    id: 'puro-plus-6-stage',
    name: 'Puro Plus (6 Stage RO+UV+UF)',
    model: 'AP-PUR-PLS6',
    category: 'Cabinet Purifiers',
    price: 14500,
    originalPrice: 17500,
    warranty: '1 Year Electrical',
    application: 'Household',
    stockStatus: 'In Stock' as const,
    featured: true,
    filterHealth: 100,
    imageUrl: 'https://res.cloudinary.com/rvoym2gw/image/upload/v1786130068/products/puro_plus.webp',
    description: 'Compact 6-stage cabinet purifier integrating RO, UV sterilizer, and UF membrane for 100% safe drinking water.'
  },
  {
    id: 'fighter-elite-7-stage',
    name: 'Fighter Elite (7 Stage RO+UV+UF)',
    model: 'AP-FGT-ELT7',
    category: 'Cabinet Purifiers',
    price: 14500,
    originalPrice: 17500,
    warranty: '1 Year Electrical',
    application: 'Household',
    stockStatus: 'In Stock' as const,
    featured: false,
    filterHealth: 100,
    imageUrl: 'https://res.cloudinary.com/rvoym2gw/image/upload/v1786130069/products/fighter_elite.webp',
    description: 'Feature-packed 7-stage cabinet purifier with multi-layer barrier protecting against pathogens and heavy metals.'
  },
  {
    id: 'fighter-1-0-7-stage',
    name: 'Fighter 1.0 (7 Stage RO+UV+UF)',
    model: 'AP-FGT-10',
    category: 'Cabinet Purifiers',
    price: 15500,
    originalPrice: 18500,
    warranty: '1 Year Electrical',
    application: 'Household',
    stockStatus: 'In Stock' as const,
    featured: false,
    filterHealth: 100,
    imageUrl: 'https://res.cloudinary.com/rvoym2gw/image/upload/v1786130070/products/fighter_1_0.webp',
    description: 'Next-generation Fighter 1.0 cabinet purifier with high-flow booster pump and automatic flush valve.'
  },
  {
    id: 'livotec-7-stage-cabinet-ro',
    name: 'Livotec 7 Stage Cabinet RO',
    model: 'AP-LIV-CAB7',
    category: 'Cabinet Purifiers',
    price: 25500,
    originalPrice: 29000,
    warranty: '1 Year Electrical',
    application: 'Household',
    stockStatus: 'In Stock' as const,
    featured: true,
    filterHealth: 100,
    imageUrl: 'https://res.cloudinary.com/rvoym2gw/image/upload/v1786130072/products/livotec_7_stage_cabinet.webp',
    description: 'Top-tier 7-stage enclosed Livotec cabinet RO purifier with luxury tempered glass aesthetics and digital TDS display.'
  },
  {
    id: 'glass-door-cabinet-ro',
    name: 'Glass Door Cabinet RO',
    model: 'AP-GLS-CAB7',
    category: 'Cabinet Purifiers',
    price: 17500,
    originalPrice: 21000,
    warranty: '1 Year Electrical',
    application: 'Household',
    stockStatus: 'In Stock' as const,
    featured: false,
    filterHealth: 100,
    imageUrl: 'https://res.cloudinary.com/rvoym2gw/image/upload/v1786130072/products/glass_door_cabinet.webp',
    description: 'Designer tempered glass front panel cabinet RO water purifier with internal food-grade storage tank.'
  },
  {
    id: 'modern-cabinet-filter',
    name: 'Modern Cabinet Filter',
    model: 'AP-MOD-CAB',
    category: 'Cabinet Purifiers',
    price: 15200,
    originalPrice: 18000,
    warranty: '1 Year Electrical',
    application: 'Household',
    stockStatus: 'In Stock' as const,
    featured: false,
    filterHealth: 100,
    imageUrl: 'https://res.cloudinary.com/rvoym2gw/image/upload/v1786130073/products/modern_cabinet_filter.webp',
    description: 'Sleek modern cabinet design with high-capacity filter cartridges and quiet operation.'
  },
  {
    id: 'slim-cabinet-purifier',
    name: 'Slim Cabinet Purifier',
    model: 'AP-SLM-CAB',
    category: 'Cabinet Purifiers',
    price: 13800,
    originalPrice: 16500,
    warranty: '1 Year Electrical',
    application: 'Household',
    stockStatus: 'In Stock' as const,
    featured: false,
    filterHealth: 100,
    imageUrl: 'https://res.cloudinary.com/rvoym2gw/image/upload/v1786130074/products/slim_cabinet_purifier.webp',
    description: 'Ultra-slim footprint cabinet purifier engineered for modern urban apartments and compact kitchens.'
  },
  {
    id: 'pure-x-100-gpd-ro-dispenser',
    name: 'Pure X 100 GPD RO Dispenser',
    model: 'AP-PUR-X100',
    category: 'Water Dispensers',
    price: 19500,
    originalPrice: 23000,
    warranty: '1 Year Electrical',
    application: 'Office',
    stockStatus: 'In Stock' as const,
    featured: true,
    filterHealth: 100,
    imageUrl: 'https://res.cloudinary.com/rvoym2gw/image/upload/v1786130075/products/pure_x_100_gpd.webp',
    description: '100 GPD commercial grade water dispenser with high recovery RO system for heavy daily demand.'
  },
  {
    id: 'heron-hot-cold-filter-dispenser',
    name: 'Heron Hot & Cold Filter Dispenser',
    model: 'AP-HER-HC',
    category: 'Water Dispensers',
    price: 21000,
    originalPrice: 25000,
    warranty: '1 Year Electrical',
    application: 'Office',
    stockStatus: 'In Stock' as const,
    featured: true,
    filterHealth: 100,
    imageUrl: 'https://res.cloudinary.com/rvoym2gw/image/upload/v1786130076/products/heron_hot_cold.webp',
    description: 'Dual temperature hot & cold water filter dispenser with compressor cooling and safety hot tap.'
  },
  {
    id: 'table-top-water-dispenser',
    name: 'Table Top Water Dispenser',
    model: 'AP-TAB-DSP',
    category: 'Water Dispensers',
    price: 18500,
    originalPrice: 21500,
    warranty: '1 Year Electrical',
    application: 'Household',
    stockStatus: 'In Stock' as const,
    featured: false,
    filterHealth: 100,
    imageUrl: 'https://res.cloudinary.com/rvoym2gw/image/upload/v1786130077/products/table_top_dispenser.webp',
    description: 'Countertop water dispenser providing instant purified drinking water without taking floor space.'
  },
  {
    id: 'puryca-premium-water-filter',
    name: 'Puryca Premium Water Filter',
    model: 'AP-PUR-PRM',
    category: 'Filters & Cartridges',
    price: 4900,
    originalPrice: 6000,
    warranty: '6 Months Warranty',
    application: 'Universal',
    stockStatus: 'In Stock' as const,
    featured: false,
    filterHealth: 100,
    imageUrl: 'https://res.cloudinary.com/rvoym2gw/image/upload/v1786130078/products/puryca_premium.webp',
    description: 'Premium multi-stage filter system delivering crystal clear drinking water and mineral enhancement.'
  },
  {
    id: 'pp-sediment-filter-cartridge',
    name: '10" / 20" PP Sediment Filter Cartridge',
    model: 'AP-PP-SED10',
    category: 'Filters & Cartridges',
    price: 450,
    originalPrice: 600,
    warranty: '6 Months Warranty',
    application: 'Universal',
    stockStatus: 'In Stock' as const,
    featured: true,
    filterHealth: 100,
    imageUrl: 'https://res.cloudinary.com/rvoym2gw/image/upload/v1786130079/products/pp_sediment_filter.webp',
    description: 'High density 5-micron polypropylene sediment cartridge for trapping rust, silt, scale, and sand particles.'
  },
  {
    id: 'cto-carbon-block-filter-cartridge',
    name: 'CTO Carbon Block Filter Cartridge',
    model: 'AP-CTO-CARB',
    category: 'Filters & Cartridges',
    price: 750,
    originalPrice: 950,
    warranty: '6 Months Warranty',
    application: 'Universal',
    stockStatus: 'In Stock' as const,
    featured: false,
    filterHealth: 100,
    imageUrl: 'https://res.cloudinary.com/rvoym2gw/image/upload/v1786130079/products/cto_carbon_block.webp',
    description: 'Extruded coconut shell activated carbon block cartridge eliminating chlorine, odor, bad taste, and organic compounds.'
  },
  {
    id: 'high-quality-ro-membrane-75-gpd',
    name: 'High-Quality RO Membrane 75 GPD',
    model: 'AP-RO-MEM75',
    category: 'Filters & Cartridges',
    price: 2200,
    originalPrice: 2800,
    warranty: '6 Months Warranty',
    application: 'Universal',
    stockStatus: 'In Stock' as const,
    featured: true,
    filterHealth: 100,
    imageUrl: 'https://res.cloudinary.com/rvoym2gw/image/upload/v1786130080/products/ro_membrane_75_gpd.webp',
    description: 'High-rejection 75 GPD reverse osmosis membrane filtering out 99% of dissolved solids, heavy metals, arsenic, and bacteria.'
  },
  {
    id: '500-lph-commercial-ro-plant',
    name: '500 LPH Commercial RO Plant',
    model: 'AP-IND-500L',
    category: 'Industrial RO Plants',
    price: 125000,
    originalPrice: 145000,
    warranty: '1 Year Electrical',
    application: 'Commercial',
    stockStatus: 'In Stock' as const,
    featured: true,
    filterHealth: 100,
    imageUrl: 'https://res.cloudinary.com/rvoym2gw/image/upload/v1786130081/products/500_lph_commercial_ro.webp',
    description: '500 Liters Per Hour heavy-duty commercial reverse osmosis plant with stainless steel frame, high-pressure pump, and pre-filtration vessels.'
  },
  {
    id: '1000-lph-industrial-ro-plant',
    name: '1000 LPH Industrial RO Plant',
    model: 'AP-IND-1000L',
    category: 'Industrial RO Plants',
    price: 245000,
    originalPrice: 280000,
    warranty: '1 Year Electrical',
    application: 'Industrial',
    stockStatus: 'In Stock' as const,
    featured: true,
    filterHealth: 100,
    imageUrl: 'https://res.cloudinary.com/rvoym2gw/image/upload/v1786130082/products/1000_lph_industrial_ro.webp',
    description: '1000 Liters Per Hour industrial scale water purification plant designed for factories, food processing, pharmaceutical, and large residential complexes.'
  }
];

export async function seed19ProductsToFirestore(): Promise<{ seededCount: number }> {
  let count = 0;
  for (const product of REAL_PRODUCTS) {
    const docRef = doc(db, PRODUCTS_COLLECTION, product.id);
    await setDoc(docRef, {
      ...product,
      createdAt: serverTimestamp(),
    }, { merge: true });
    count++;
  }
  return { seededCount: count };
}
